export declare const env: {
    NODE_ENV: any;
    LOG_LEVEL: any;
    IE_COMPAT: boolean;
    TEST_MODE: boolean;
};
export declare const isDevelopment: boolean;
export declare const isDev: boolean;
export declare const isProduction: boolean;
export declare const isProd: boolean;
export declare const logGtEqlSilly: boolean;
export declare const logGtEqlVerbose: boolean;
export declare const logGtEqlDebug: boolean;
export declare const logGtEqlInfo: boolean;
export declare const logGtEqlWarn: boolean;
export declare const logGtEqlError: boolean;
export declare const logGtEqlWTF: boolean;
export declare const logGtEqlWtf: boolean;
export declare const isSilly: boolean;
export declare const isVerbose: boolean;
export declare const isDebug: boolean;
export declare const isInfo: boolean;
export declare const isWarn: boolean;
export declare const isError: boolean;
export declare const isWTF: boolean;
export declare const isWtf: boolean;
export declare const isLogSilly: boolean;
export declare const isLogVerbose: boolean;
export declare const isLogDebug: boolean;
export declare const isLogInfo: boolean;
export declare const isLogWarn: boolean;
export declare const isLogError: boolean;
export declare const isLogWTF: boolean;
export declare const isLogWtf: boolean;
export declare const isIeCompatMode: boolean;
export declare const isIECompatMode: boolean;
export declare const isIECompat: boolean;
export declare const isIeCompat: boolean;
export declare const isTestMode: boolean;
